database:
  host: 127.0.0.1
  port: 3306
  username: user
  password: password
  database: database

gateways:
  MERCADO_PAGO:
    authentication: "token"

discord:
  token: "TOKEN"

categories:
  Example:
    name: "Categoria Exemplo"
    description:
      - ""
    icon:
      material: DIAMOND
      id: 0